title:            Sumendar Karupakala
description:      homepage
# Your site's domain goes here. Leave localhost server or blank when working locally.
# url:              http://localhost:4000
# url:              https://sumendar.github.io
  url:              http://www.sumendar.com
disqus_shortname:

# Owner/author information
owner:
  name:           Sumendar Karupakala
  avatar:         bio-photo.jpg
  bio:            "Data Science Data Journalism Open Data Big Data Data Visualisation"
  email:          andrewbrooksct@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:       sumendar
  facebook:
  github:        sumendar
  stackoverflow:
  linkedin:      sumendar
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: "UA-52978786-1"
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: https://sumendar.github.io/simpleblog
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
